# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Oco
                                 A QGIS plugin
 Faz layout das ocorrencias, morfo, pranchas e relatorio
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-02-24
        copyright            : (C) 2021 by Romario Moraes Carvalho Neto
        email                : romariocarvalho@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software, you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation, either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Oco class from file Oco.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .oco import Oco
    return Oco(iface)
